id = "symbols-icon-theme"
name = "Symbols Icon Theme"
version = "0.0.24"
schema_version = 1
authors = ["gilmar-sales"]
description = "Symbols icons ported from vscode."
repository = "https://github.com/gilmar-sales/symbols-icon-theme-zed"
